# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Test"

#
# Based on workflows from other projects:
# 
# * https://github.com/composer/composer/blob/2.9.8/.github/workflows/continuous-integration.yml
# * https://github.com/composer/installers/blob/v2.2.0/.github/workflows/continuous-integration.yml
# * https://github.com/ramsey/composer-install/blob/4.0.0/.github/workflows/continuous-integration.yml
#

on:
  pull_request: ~
  push: ~
  schedule:
    # Once monthly on 15th at 15:00 UTC to test
    # on latest versions of Composer and PHP.
    #
    #        ┌─────────────── minute           (0 - 59)
    #        │   ┌─────────── hour             (0 - 23)
    #        │   │   ┌─────── day of the month (1 - 31)
    #        │   │   │  ┌──── month            (1 - 12 or JAN-DEC)
    #        │   │   │  │  ┌─ day of the week  (0 - 6 or SUN-SAT)
    #        │   │   │  │  │
    - cron: '0  15  15  *  *'
  workflow_dispatch: ~

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"

permissions:
  contents: read

jobs:
  tests:
    name: "PHP ${{ matrix.php-version }} / Composer ${{ matrix.composer-version }} / ${{ matrix.os }}"

    strategy:
      matrix:
        php-version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        composer-version:
          - "2.9"
        os:
          - "ubuntu-latest"
        experimental:
          - false
        include:
          - php-version: "8.4"
            composer-version: "preview"
            os: "ubuntu-latest"
            experimental: true
          - php-version: "8.4"
            composer-version: "snapshot"
            os: "ubuntu-latest"
            experimental: true
          - php-version: "8.4"
            composer-version: "v2"
            os: "windows-latest"
            experimental: false
          - php-version: "8.6"
            composer-version: "v2"
            os: "ubuntu-latest"
            experimental: true

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10" # v6.0.3
        with:
          persist-credentials: false

      - name: "Prepare git environment"
        run: "git config --global user.name composer && git config --global user.email composer@example.com"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc" # 2.37.1
        with:
          coverage: "none"
          extensions: "intl, zip"
          ini-values: "memory_limit=-1, error_reporting=E_ALL, display_errors=On"
          php-version: "${{ matrix.php-version }}"
          tools: composer:${{ matrix.composer-version }}

      - name: "Install Composer dependencies"
        shell: bash
        env:
          COMPOSER_VERSION: ${{ matrix.composer-version }}
        run: |
          if [ "$COMPOSER_VERSION" == "snapshot" ]; then
            composer config platform --unset
            composer config minimum-stability dev
            composer require $COMPOSER_FLAGS --update-with-dependencies --dev composer/composer="dev-main"
          elif [ "$COMPOSER_VERSION" == "preview" ]; then
            composer config platform --unset
            composer config minimum-stability alpha
            composer require $COMPOSER_FLAGS --update-with-dependencies --dev composer/composer
          elif [ "$COMPOSER_VERSION" == "v2" ]; then
            composer install $COMPOSER_FLAGS
          else
            composer require $COMPOSER_FLAGS --update-with-dependencies --dev composer/composer="~$COMPOSER_VERSION.0"
          fi

      - name: "Install PHPUnit"
        run: "./vendor/bin/simple-phpunit install"

      - name: "Run tests"
        run: "./vendor/bin/simple-phpunit --verbose"
